import { useState } from 'react'
import { toast } from 'sonner'
import { ArrowUpRight, BookOpen, Check, ChevronRight, Copy, Download, Fingerprint, LockKeyhole, Radio, Shield, Webhook } from 'lucide-react'
import { Button, PageHeader } from '../components/Ui'

const docSections = [
  { id: 'overview', title: 'Platform overview', group: 'GETTING STARTED' },
  { id: 'sensors', title: 'Connect a sensor', group: 'DATA INGESTION' },
  { id: 'api', title: 'Ingest API reference', group: 'DATA INGESTION' },
  { id: 'suricata', title: 'Suricata integration', group: 'INTEGRATIONS' },
  { id: 'zeek', title: 'Zeek integration', group: 'INTEGRATIONS' },
  { id: 'wazuh', title: 'Wazuh integration', group: 'INTEGRATIONS' },
  { id: 'security', title: 'Security model', group: 'PLATFORM' },
  { id: 'deploy', title: 'Deployment guide', group: 'PLATFORM' },
]

function CodeBlock({ code, language = 'bash' }: { code: string; language?: string }) {
  const [copied, setCopied] = useState(false)
  const copy = async () => { try { await navigator.clipboard.writeText(code); setCopied(true); toast.success('Copied to clipboard'); setTimeout(() => setCopied(false), 1400) } catch { toast.error('Clipboard unavailable') } }
  return <div className="docs-code"><div className="docs-code-header"><span><i />{language}</span><button onClick={copy}>{copied ? <Check size={13} /> : <Copy size={13} />}{copied ? 'Copied' : 'Copy'}</button></div><pre>{code}</pre></div>
}

export default function DocsPage() {
  const [active, setActive] = useState('overview')
  const go = (id: string) => { setActive(id); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
  return <div className="page docs-page">
    <PageHeader eyebrow="KNOWLEDGE BASE" title="Documentation" description="Integrate telemetry, configure response, and deploy NetDefender in your environment." actions={<Button variant="secondary" onClick={() => toast.info('Documentation download', { description: 'The printable deployment guide is being prepared.' })}><Download size={15} /> Download guide</Button>} />
    <div className="docs-layout"><aside className="docs-sidebar"><label className="docs-search"><BookOpen size={14} /><input placeholder="Search documentation" onChange={(event) => { const match = docSections.find((section) => section.title.toLowerCase().includes(event.target.value.toLowerCase())); if (match && event.target.value) setActive(match.id) }} /></label><div className="docs-nav">{['GETTING STARTED', 'DATA INGESTION', 'INTEGRATIONS', 'PLATFORM'].map((group) => <div className="docs-nav-group" key={group}><span>{group}</span>{docSections.filter((item) => item.group === group).map((item) => <button className={active === item.id ? 'docs-link docs-link-active' : 'docs-link'} key={item.id} onClick={() => go(item.id)}>{item.title}{active === item.id && <ChevronRight size={13} />}</button>)}</div>)}</div><div className="docs-help-card"><div><BookOpen size={15} /></div><b>Need a hand?</b><p>Talk to a security engineer about your deployment.</p><button onClick={() => toast.info('Support request', { description: 'A NetDefender support engineer will be in touch.' })}>Contact support <ArrowUpRight size={13} /></button></div></aside>
      <article className="docs-content">
        <section id="overview" className="doc-section"><div className="doc-breadcrumb">Docs <ChevronRight size={13} /> Getting started</div><span className="doc-section-tag">INTRODUCTION</span><h2>NetDefender security operations</h2><p className="doc-lead">NetDefender is a real-time network intrusion detection and prevention control plane. It unifies sensor telemetry, automated containment, firewall policy, and incident workflows in one SOC workspace.</p><div className="docs-feature-grid"><div><span><Radio size={16} /></span><b>Observe</b><p>Stream events from Suricata, Zeek, and Wazuh into a normalized alert queue.</p></div><div><span><Shield size={16} /></span><b>Respond</b><p>Contain suspicious sources and orchestrate automated response playbooks.</p></div><div><span><Fingerprint size={16} /></span><b>Prove</b><p>Track every action in an auditable event history with role-based access.</p></div></div><div className="docs-callout"><LockKeyhole size={17} /><span><b>Demo environment</b><br />This workspace runs with seeded demo telemetry until Supabase credentials are configured. No production traffic is monitored by default.</span></div></section>
        <section id="sensors" className="doc-section"><span className="doc-section-tag">DATA INGESTION</span><h2>Connect a sensor</h2><p>Each sensor sends normalized event payloads to the <code>/functions/v1/ingest-alert</code> endpoint. Create a hashed API key from <b>Settings → API keys</b>, then store it securely in your sensor secret manager.</p><ol className="docs-steps"><li><span>1</span><div><b>Generate an ingest key</b><p>Create a key per environment and scope it to the telemetry pipeline.</p></div></li><li><span>2</span><div><b>Configure your forwarder</b><p>Send enriched alerts as JSON over TLS. Never embed keys in client-side code.</p></div></li><li><span>3</span><div><b>Verify sensor health</b><p>Confirm heartbeat and event volume in the Sensors page.</p></div></li></ol></section>
        <section id="api" className="doc-section"><span className="doc-section-tag">API REFERENCE</span><h2>Ingest API</h2><div className="api-endpoint"><span className="http-method">POST</span><code>/functions/v1/ingest-alert</code><span className="api-auth-tag"><LockKeyhole size={12} /> API key required</span></div><p>Submit a network alert event. Requests are validated, rate-limited, enriched with server-side metadata, and written to the alerts table.</p><CodeBlock language="bash" code={`curl -X POST "$SUPABASE_URL/functions/v1/ingest-alert" \\
  -H "Authorization: Bearer $NETDEFENDER_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{
    "severity": "high",
    "source_ip": "185.220.101.45",
    "source_country": "Russia",
    "destination_ip": "10.24.1.42",
    "protocol": "TCP",
    "attack_type": "SSH Brute Force",
    "signature": "ET POLICY SSH brute force attempt"
  }'`} /><div className="docs-field-table"><div><b>Field</b><b>Type</b><b>Required</b><b>Description</b></div><div><code>severity</code><span>string</span><span>Yes</span><span>low · medium · high · critical</span></div><div><code>source_ip</code><span>IPv4</span><span>Yes</span><span>External source address</span></div><div><code>attack_type</code><span>string</span><span>Yes</span><span>Normalized threat classification</span></div><div><code>raw_log</code><span>string</span><span>No</span><span>Original sensor payload / signature</span></div></div></section>
        <section id="suricata" className="doc-section"><span className="doc-section-tag">INTEGRATIONS</span><h2>Suricata integration</h2><p>Use EVE JSON output and a lightweight forwarder to map Suricata alerts to the NetDefender ingest schema.</p><CodeBlock language="yaml" code={`# suricata.yaml\neve-log:\n  enabled: yes\n  filetype: regular\n  filename: eve.json\n  types:\n    - alert:\n        payload: yes\n        metadata: yes\n    - http\n    - dns\n    - flow`} /><div className="docs-tip"><Webhook size={15} /><span>Map <code>alert.signature</code> to <code>signature</code>, <code>src_ip</code> to <code>source_ip</code>, and normalize severity using your organization’s severity policy.</span></div></section>
        <section id="zeek" className="doc-section"><span className="doc-section-tag">INTEGRATIONS</span><h2>Zeek integration</h2><p>Zeek connection and notice logs can be shipped with Filebeat, Vector, or a custom script. Use the notice framework for higher-confidence detections.</p><CodeBlock language="json" code={`{\n  "source_ip": "${'{'}id.orig_h}",\n  "destination_ip": "${'{'}id.resp_h}",\n  "protocol": "${'{'}proto}",\n  "attack_type": "${'{'}note}",\n  "severity": "medium",\n  "signature": "Zeek Notice Framework"\n}`} /><p>Map Intel and Notice records to alert events. Preserve the original log record in <code>raw_log</code> for investigation and evidence retention.</p></section>
        <section id="wazuh" className="doc-section"><span className="doc-section-tag">INTEGRATIONS</span><h2>Wazuh integration</h2><p>Forward Wazuh manager alerts using the integration webhook. Enrich the alert with agent metadata before sending it to the ingest API.</p><CodeBlock language="xml" code={`<integration>\n  <name>custom-netdefender</name>\n  <hook_url>https://YOUR_PROJECT.supabase.co/functions/v1/ingest-alert</hook_url>\n  <level>7</level>\n  <alert_format>json</alert_format>\n</integration>`} /></section>
        <section id="security" className="doc-section"><span className="doc-section-tag">SECURITY</span><h2>Security model</h2><ul className="docs-bullets"><li><b>Row Level Security:</b> role-based policies restrict table access. Viewers are read-only; analysts may update alert and incident workflow; admins manage configuration.</li><li><b>Profile roles:</b> an Auth trigger creates a <code>profiles</code> row as <code>viewer</code> on signup. Role changes never trust signup metadata and must be made by a trusted workspace administrator.</li><li><b>API key hygiene:</b> hash service keys at rest, rotate credentials, and never expose the service role key in a browser.</li><li><b>Transport:</b> use HTTPS for every sensor and webhook connection. Restrict ingest access by network policy where possible.</li><li><b>Auditability:</b> administrative changes are written to the append-only audit log.</li></ul></section>
        <section id="deploy" className="doc-section"><span className="doc-section-tag">DEPLOYMENT</span><h2>Deployment guide</h2><ol className="docs-steps"><li><span>1</span><div><b>Create a Supabase project</b><p>Apply the included migrations, enable email auth, and add your redirect URLs.</p></div></li><li><span>2</span><div><b>Deploy Edge Functions</b><p>Configure secrets for API key hashing, firewall webhook, Resend, and Slack integrations. Apply the playbook automation migration before deploying its evaluator.</p></div></li><li><span>3</span><div><b>Set frontend environment variables</b><p>Configure the public project URL and anon key using <code>.env.example</code>.</p></div></li><li><span>4</span><div><b>Seed and verify</b><p>Load demo fixtures in a non-production project and verify subscriptions, alerts, and role policies.</p></div></li></ol><CodeBlock language="bash" code={`supabase db push\n# Local-only: db reset also runs supabase/seed.sql\nsupabase db reset\nsupabase functions deploy ingest-alert\nsupabase functions deploy block-ip\nsupabase functions deploy simulate-traffic\nsupabase functions deploy send-notification\nsupabase functions deploy evaluate-playbooks\nsupabase functions deploy expire-blocks\nsupabase functions deploy manage-api-keys\nnpm run build`} /><div className="docs-final-note"><Check size={15} /> Documentation applies to NetDefender v2.4 · Updated October 2026</div></section>
        <div className="docs-next-page"><span>INTEGRATIONS</span><b>Sensor onboarding reference</b><button onClick={() => go('sensors')}>Connect your first sensor <ArrowUpRight size={14} /></button></div>
      </article></div>
  </div>
}
